<?php
    $users = $viewData['users'];
?>

<h1 class="page-header">Users</h1>

<a href="/crud/insert">Insert</a>
<div class="table-responsive">
    <table class="table table-striped table-condensed table-hover">

        <thead>
            <tr>
                <?php foreach($users[0] as $id => $user):?>
                    <th><?=$id?></th>
                <?php endforeach; ?>
            </tr>
        </thead>

        <tbody>
            <?php foreach($users as $id => $user):?>
                <tr>
                   <?php
                    foreach ($user as $value):?>
                        <td><?php echo $value;?></td>
                    <?php endforeach; ?>
                    <td>
                        <a href="/crud/update/id/<?=$user['iduser'];?>">Update</a> |
                        <a href="/crud/delete/id/<?=$user['iduser'];?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
